// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Model/produto.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1540572822767725651),
      name: 'Produto',
      lastPropertyId: const IdUid(5, 2098022451531953071),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3742766278558671778),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 347157492643116571),
            name: 'nome',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7912027791326161504),
            name: 'tags',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5249762723112286768),
            name: 'precoBase',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2098022451531953071),
            name: 'imagem',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 1540572822767725651),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Produto: EntityDefinition<Produto>(
        model: _entities[0],
        toOneRelations: (Produto object) => [],
        toManyRelations: (Produto object) => {},
        getId: (Produto object) => object.id,
        setId: (Produto object, int id) {
          object.id = id;
        },
        objectToFB: (Produto object, fb.Builder fbb) {
          final nomeOffset = fbb.writeString(object.nome);
          final tagsOffset = fbb.writeList(
              object.tags.map(fbb.writeString).toList(growable: false));
          final imagemOffset = fbb.writeString(object.imagem);
          fbb.startTable(6);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nomeOffset);
          fbb.addOffset(2, tagsOffset);
          fbb.addFloat64(3, object.precoBase);
          fbb.addOffset(4, imagemOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Produto(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              nome: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              tags: const fb.ListReader<String>(
                      fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 8, []),
              precoBase:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0),
              imagem: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Produto] entity fields to define ObjectBox queries.
class Produto_ {
  /// see [Produto.id]
  static final id = QueryIntegerProperty<Produto>(_entities[0].properties[0]);

  /// see [Produto.nome]
  static final nome = QueryStringProperty<Produto>(_entities[0].properties[1]);

  /// see [Produto.tags]
  static final tags =
      QueryStringVectorProperty<Produto>(_entities[0].properties[2]);

  /// see [Produto.precoBase]
  static final precoBase =
      QueryDoubleProperty<Produto>(_entities[0].properties[3]);

  /// see [Produto.imagem]
  static final imagem =
      QueryStringProperty<Produto>(_entities[0].properties[4]);
}
